{% set name = "antlr4-cpp-runtime" %}
{% set version = "4.9.3" %}
{% set version_patch = ".junttila" %}
{% set full_version = version + version_patch %}

package:
  name: {{ name|lower }}
  # version: {{ version }}.0{{ version_patch.replace("-", "_") }}
  version: {{ version }}

source:
  url: https://www.antlr.org/download/antlr4-cpp-runtime-4.9.3-source.zip
  sha256: 5f0af6efd81f476c3e775c486eb0a71c25d6bbc14373e88a64690e2738d68e03

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make

# test:
#   requires:
#     - {{ compiler('cxx') }}
#   files:
#     - test_app.cpp
#   commands:
#     - test -f "$PREFIX/include/bliss/graph.hh"
#     - test -f "$PREFIX/lib/libbliss${SHLIB_EXT}"
#     - $CXX $CXXFLAGS $LDFLAGS test_app.cpp -o test_app -lbliss && ./test_app
#     - bliss -help

about:
  home: https://www.antlr.org/
  license: BSD 3-clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'ANTLR (ANother Tool for Language Recognition) is a powerful parser generator for reading, processing, executing, or translating structured text or binary files.'

extra:
  recipe-maintainers:
    - katanagraph
    - amp
