{% set name = "bliss" %}
{% set version = "0.77" %}
{% set version_patch = ".junttila" %}
{% set full_version = version + version_patch %}

package:
  name: {{ name|lower }}
  version: {{ version }}.0{{ version_patch.replace("-", "_") }}

source:
  url: https://users.aalto.fi/~tjunttil/bliss/downloads/bliss-0.77.zip
  sha256: acc8b98034f30fad24c897f365abd866c13d9f1bb207e398d0caf136875972a4

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - libtool
    - cmake
    - make

test:
  commands:
    - test -f "$PREFIX/include/bliss/graph.hh"
    - test -f "$PREFIX/lib/libbliss${SHLIB_EXT}"

about:
  home: https://users.aalto.fi/~tjunttil/bliss/index.html
  license: LGPL3
  license_family: LGPL
  license_file: COPYING.LESSER
  summary: 'bliss is an open-source tool for computing canonical labelings and automorphism groups of graphs.'

extra:
  recipe-maintainers:
    - katanagraph
    - amp
