travis:
  secure:
    BINSTAR_TOKEN: Qmvo1pIzBHCgbtCVmI1bKOudx4lZrd/GZx8D8CutruQbI+tAuGnk7irUvosCGaJRR3xnXuyUlL6j7qQsjDAAynnyK8SV5tkqxzHVKsKSVmAWxO0HLpcdsqTu4Rls8cf1uNLmVAimG6ve4/ExCDPg1qiymIvQ6Jvox6TIlzrhBFTBxoI3r7EAk+MQyqmihVovbpVdm+Igp2nntQZLX3JrYXf0U13f9gUhYyTrQUR/D3Q6EMtIZmm3OQpthyUWltDp9+ZzuwKT28MlLsuYqQYG+aKb4TcqIk0JHjnap3Ty2uwNB2phzoGUut37f/2O9Et3wADhhWeOTf6DdQpPh2YBisWFx0Hy/bl/frNckNCSrVS6kOjtqqYv39NyF8vUcDS24+MkKEPDJuVQw/lfHFfBPbBw1mLi/dq3oOb1Hk6IdWALIvCVturbuLv5wUflXz2W3SfvOPc97zTSBX2UAxQrhqR4oHBt+4mKuOx+aCCY2QDXFyJYSAX5ouutu9ZN9RcSUAbvwpf7wqioomqGNAGcx89EkYWOw2pXrUw0A8RxNa3/zXaBFl+h9r0rnuYFTHAixDdmQHFFm1YNpEBugvUj4qQhy0giQWn4WAFtfckSHauqH3qq3jbtph4a+Swp8dvv9a6cUNvx+x1rM6+PdizA3ahg02C77Dn2NqRm+FL12lw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
